name: Update IP every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Update IP address
        run: "echo Current IP: $(curl -s https://ip8.com/ip) > README.md"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update IP address"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: EndBug/push@v2
        with:
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
